apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 50m
